<?php

namespace Sie\EsquemaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * especialidadSuperiorTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class especialidadSuperiorTipoRepository extends EntityRepository
{
}
