<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BjpEstudianteApoderadoPagadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BjpEstudianteApoderadoPagadosRepository extends EntityRepository
{
}
