<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BonojuancitoAsignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonojuancitoAsignacionRepository extends EntityRepository
{

  public function getInfoAsignacion($data) {
      $qb = $this->getEntityManager()->createQueryBuilder();
      $qb
              ->select('(bjpa.id) as bjpaId, bjpum.id as bjpumid, bjpum.unidadmilitar, bjpa.institucioneducativa, bjpa.codSie as rue, bjpa.departamentoTipoId, bjpa.departamentoTipo, bjpa.provincia,
                        bjpa.municipio, bjpa.seccion, bjpa.canton, bjpa.localidad, bjpft.fuerza,bjpa.esterminado
                        ')
              ->from('SieAppWebBundle:BonojuancitoAsignacion', 'bjpa')
              ->leftjoin('SieAppWebBundle:BonojuancitoUnidadmilitar', 'bjpum', 'WITH', 'bjpa.bonojuancitoUnidadmilitar = bjpum.id')
              ->leftjoin('SieAppWebBundle:BonojuancitoGranUnidadmilitar', 'bjpgum', 'WITH', 'bjpum.bonojuancitoGranUnidadmilitar = bjpgum.id')
              ->leftjoin('SieAppWebBundle:BonojuancitoFuerzaTipo', 'bjpft', 'WITH', 'bjpgum.bonojuancitoFuerzaTipo = bjpft.id')
              ->where('bjpa.codSie = :sie')
              ->setParameter('sie', $data['sie'])
      ;
      return $qb->getQuery()->getResult();
  }
  
  public function getInfoAgenteUnidad($sie) {
      $qb = $this->getEntityManager()->createQueryBuilder();
      $qb
              ->select('(bjpa.id) as bjpaId, bjpum.unidadmilitar, bjpa.institucioneducativa,
                         bjpa.codSie as rue, bjpa.departamentoTipoId, bjpa.departamentoTipo, bjpa.provincia,
                        bjpa.municipio, bjpa.seccion, bjpa.canton, bjpa.localidad, bjpft.fuerza,bjpa.esterminado,
                        bjpa.orgcurricularTipo, bjpa.areaGeografica, bjpa.distrito, bjpa.turno, bjpa.pagadoEnPeriodo, bjpa.pagadoRezagado, bjpa.totalPlanificado
                        ')
              ->from('SieAppWebBundle:BonojuancitoAsignacion', 'bjpa')
              ->leftjoin('SieAppWebBundle:BonojuancitoUnidadmilitar', 'bjpum', 'WITH', 'bjpa.bonojuancitoUnidadmilitar = bjpum.id')
              ->leftjoin('SieAppWebBundle:BonojuancitoGranUnidadmilitar', 'bjpgum', 'WITH', 'bjpum.bonojuancitoGranUnidadmilitar = bjpgum.id')
              ->leftjoin('SieAppWebBundle:BonojuancitoFuerzaTipo', 'bjpft', 'WITH', 'bjpgum.bonojuancitoFuerzaTipo = bjpft.id')
              ->where('bjpa.codSie = :sie')
              ->setParameter('sie', $sie)
      ;
      return $qb->getQuery()->getResult();
  }
  
  /*
  estudiantes
  */
  public function getEstudiantesBono($form,$pagado, $habilitado) {
      $qb = $this->getEntityManager()->createQueryBuilder();
      $qb
              ->select('bjp.codigoRude, bjp.id, bjp.nombre, bjp.paterno, bjp.materno, bjp.fechaNacimiento ,bjp.espagado, bjp.eshabilitado, bjp.esnuevorude')
              ->from('SieAppWebBundle:BonojuancitoPaga', 'bjp')
              ->andwhere('bjp.institucioneducativa = :id')
              ->andwhere('bjp.gestionTipo = :gestion')
              ->andwhere('bjp.nivelTipo = :nivel')
              ->andwhere('bjp.gradoTipo = :grado')
              ->andwhere('bjp.paraleloTipo = :paralelo')
              ->andwhere('bjp.espagado = :pagado')
              ->andwhere('bjp.eshabilitado = :habilitado')
              ->setParameter('id', $form['idInstitucion'])
              ->setParameter('gestion', $form['idGestion']-1)
              ->setParameter('nivel', $form['nivel'])
              ->setParameter('grado', $form['grado'])
              ->setParameter('paralelo', $form['paralelo'])
              ->setParameter('pagado', $pagado)
              ->setParameter('habilitado', $habilitado);
      ;
      return $qb->getQuery()->getResult();
  }
public function getAsignacionInstituciones() {
      $qb = $this->getEntityManager()->createQueryBuilder();
      $qb
              ->select ('bja.institucioneducativa, bjpft.fuerza, bjpum.unidadmilitar, bja.institucioneducativa, bja.codSie, bja.departamentoTipo, bja.municipio, bja.distrito, bja.esterminado, bja.registrados, bja.pagadoEnPeriodo, bja.pagadoRezagado, bja.noRecibieron')
              ->from('SieAppWebBundle:BonojuancitoAsignacion', 'bja')
              ->leftjoin('SieAppWebBundle:BonojuancitoUnidadmilitar', 'bjpum', 'WITH', 'bja.bonojuancitoUnidadmilitar = bjpum.id')
              ->leftjoin('SieAppWebBundle:BonojuancitoGranUnidadmilitar', 'bjpgum', 'WITH', 'bjpum.bonojuancitoGranUnidadmilitar = bjpgum.id')
              ->leftjoin('SieAppWebBundle:BonojuancitoFuerzaTipo', 'bjpft', 'WITH', 'bjpgum.bonojuancitoFuerzaTipo = bjpft.id')
              ;
      return $qb->getQuery()->getResult();
  }

  public function getRegistroResultados() {
      $qb = $this->getEntityManager()->createQueryBuilder();
      $qb
              ->select ('bja.institucioneducativa, bjpft.fuerza, bjpum.unidadmilitar, bja.institucioneducativa, bja.codSie, bja.departamentoTipo, bja.municipio, bja.distrito, bja.espagado, bja.esterminado, bja.registrados, bja.pagadoEnPeriodo, bja.pagadoRezagado, bja.noRecibieron')
              ->from('SieAppWebBundle:BonojuancitoAsignacion', 'bja')
              ->leftjoin('SieAppWebBundle:BonojuancitoUnidadmilitar', 'bjpum', 'WITH', 'bja.bonojuancitoUnidadmilitar = bjpum.id')
              ->leftjoin('SieAppWebBundle:BonojuancitoGranUnidadmilitar', 'bjpgum', 'WITH', 'bjpum.bonojuancitoGranUnidadmilitar = bjpgum.id')
              ->leftjoin('SieAppWebBundle:BonojuancitoFuerzaTipo', 'bjpft', 'WITH', 'bjpgum.bonojuancitoFuerzaTipo = bjpft.id')
              ;
      return $qb->getQuery()->getResult();
  }
  
}
