<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ControlArchivosBajadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControlOperativoEspecialRepository extends EntityRepository
{
    public function detalleControl($gestion, $area,$nivel, $programa, $servicio, $tecnica) {


        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
                ->select('*')
                ->from('SieAppWebBundle:ControlOperativoEspecial', 'c')
                ->where('c.gestionTipoId = :gestion')
                ->andwhere('c.especialAreaTipoId = :area')
                ->andwhere('c.nivelTipoId = :nivel')
                ->andwhere('c.especialProgramaTipoId = :programa')
                ->andwhere('c.especialServicioTipoId = :servicio')
                ->andwhere('c.especialEspecialidadTecnicaId = :tecnica')
                ->setParameter('gestion', $gestion)
                ->setParameter('nivel', $nivel)
                ->setParameter('area', $area)
                ->setParameter('programa', $programa)
                ->setParameter('servicio', $servicio)
                ->setParameter('tecnica', $tecnica)
        ;
        return $qb->getQuery()->getResult();
    }

}
