<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DistritoTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistritoTipoRepository extends EntityRepository {

    /**
     * get info distrito and departamento
     * @param type $dis
     * @return arraya with distrito and departamento
     */
    public function getInfoDepByDistrito($dis) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
                ->select('dit.id , dit.distrito, det.departamento')
                ->from('SieAppWebBundle:DistritoTipo', 'dit')
                ->leftjoin('SieAppWebBundle:DepartamentoTipo', 'det', 'WITH', 'dit.departamentoTipo = det.id')
                ->where('dit.id = :dis')
                ->setParameter('dis', $dis)

        ;

        return $qb->getQuery()->getResult();
    }

}
