<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstTecCargoJerarquicoTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstTecCargoJerarquicoTipoRepository extends EntityRepository
{
}
