<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstTecInstitutoCarreraEstudianteEstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstTecInstitutoCarreraEstudianteEstadoRepository extends EntityRepository
{
}
