<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstudianteInscripcionHumnisticoTecnicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudianteInscripcionHumnisticoTecnicoRepository extends EntityRepository {/*
 * select * 
  from estudiante_inscripcion_humnistico_tecnico eth
  left join estudiante_inscripcion ei on (eth.estudiante_inscripcion_id=ei.id)
  left join estudiante e on (ei.estudiante_id = e.id)
  left join institucioneducativa_curso iec on (ei.institucioneducativa_curso_Id = iec.id)
  where iec.institucioneducativa_id = '80480072' and iec.gestion_tipo_id = '2015'
 */

    public function getStudentsTecHum($id, $gestion) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
                ->select('e.codigoRude, e.carnetIdentidad, e.paterno, e.materno, e.nombre, g.genero, pt.pais, lt.lugar, e.localidadNac,etht.especialidad,eth.horas ')
                ->from('SieAppWebBundle:EstudianteInscripcionHumnisticoTecnico', 'eth')
                ->leftjoin('SieAppWebBundle:EstudianteInscripcion', 'ei', 'WITH', 'eth.estudianteInscripcionId = ei.id')
                ->leftjoin('SieAppWebBundle:Estudiante', 'e', 'WITH', 'ei.estudiante = e.id')
                ->leftjoin('SieAppWebBundle:GeneroTipo', 'g', 'WITH', 'e.generoTipo = g.id')
                ->leftjoin('SieAppWebBundle:PaisTipo', 'pt', 'WITH', 'e.paisTipo = pt.id')
                ->leftjoin('SieAppWebBundle:LugarTipo', 'lt', 'WITH', 'e.lugarNacTipo = lt.id ')
                ->leftjoin('SieAppWebBundle:InstitucioneducativaCurso', 'iec', 'WITH', 'ei.institucioneducativaCurso = iec.id')
                ->leftjoin('SieAppWebBundle:EspecialidadTipoHumnisticoTecnico', 'etht', 'WITH', 'eth.especialidadTipo = etht.id')
                ->where('iec.institucioneducativa = :id')
                ->andwhere('iec.gestionTipo = :gestion')
                ->setParameter('id', $id)
                ->setParameter('gestion', $gestion)
                ->orderBy('etht.especialidad')
        ;
        return $qb->getQuery()->getResult();
    }

}
