<?php

//

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstudiantenoacredidatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudiantenoacredidatoRepository extends EntityRepository {

    /**
     * get the infot abuot unacredits students
     * @param type $id
     * @return array with infot about students
     */
    public function getInfoEstudianteNoAcreditado($id) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
                ->select('ena.id, IDENTITY(ena.institucioneducativanoacreditada) as ienoacreditada,ena.carnetIdentidad', 'ena.paterno, ena.materno, ena.nombre, ena.fechaNacimiento, ena.generoTipoId, nt.nivel, gt.grado, ena.paralelo, tt.turno')
                ->from('SieAppWebBundle:Estudiantenoacredidato', 'ena')
                ->leftjoin('SieAppWebBundle:NivelTipo', 'nt', 'WITH', 'ena.nivelId = nt.id')
                ->leftjoin('SieAppWebBundle:GradoTipo', 'gt', 'WITH', 'ena.gradoId = gt.id')
                //->leftjoin('SieAppWebBundle:ParaleloTipo', 'pt', 'WITH', 'ena.paralelo =  cast(pt.id as INTEGER)')
                ->leftjoin('SieAppWebBundle:TurnoTipo', 'tt', 'WITH', 'ena.turnoId = tt.id')
                ->where('ena.institucioneducativanoacreditada = :id')
                ->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }

}
