<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfraestructuraH4AmbientepedagogicoDeportivoEquimientoTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfraestructuraH4AmbientepedagogicoDeportivoEquimientoTipoRepository extends EntityRepository
{
}
