<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfraestructuraH2CaracteristicaEdificacionSenalesTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfraestructuraH2CaracteristicaEdificacionSenalesTipoRepository extends EntityRepository
{
}
