<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfraestructuraH1AccesoFluvialTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfraestructuraH1AccesoFluvialTipoRepository extends EntityRepository
{
}
