<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfraestructuraH5AmbienteadministrativoInmobiliarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfraestructuraH5AmbienteadministrativoInmobiliarioRepository extends EntityRepository
{
}
