<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfraestructuraH6EquipamientoPedagogicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfraestructuraH6EquipamientoPedagogicoRepository extends EntityRepository
{
}
