<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfraestructuraJuridiccionGeograficaMunicipioCentroideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfraestructuraJuridiccionGeograficaMunicipioCentroideRepository extends EntityRepository
{
}
