<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfraestructuraH2CaracteristicaEdificadosPisosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfraestructuraH2CaracteristicaEdificadosPisosRepository extends EntityRepository
{
}
