<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfraestructuraH6EquipamientoViviendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfraestructuraH6EquipamientoViviendaRepository extends EntityRepository
{
}
