<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InstitucioneducativaSucursalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitucioneducativaSucursalRepository extends EntityRepository
{
    public function getOneSucursalTipo($ie_id, $ie_gestion) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
                ->select('b.id')
                ->from('SieAppWebBundle:InstitucioneducativaSucursal', 'a')
                ->innerJoin('SieAppWebBundle:SucursalTipo', 'b', 'WITH', 'b.id = a.sucursalTipo')
                ->innerJoin('SieAppWebBundle:Institucioneducativa', 'c', 'WITH', 'c.id = a.institucioneducativa')
                ->where('c.id = '.$ie_id)
                ->andWhere('a.gestionTipo = '.$ie_gestion)
                ->groupBy('b.id')
                ->orderBy('b.id')
                ;
        
        return $qb->getQuery()->getResult();
    }
    
    public function getAllSucursalTipo($ie_id) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
                ->select('d.id as gestionTipo, b.id as SucursalIE, a.id as IEsucursalId, a.periodoTipoId, h.id as teid, h.tramiteEstado as te, h.obs as observacion')
                ->from('SieAppWebBundle:InstitucioneducativaSucursal', 'a')
                ->innerJoin('SieAppWebBundle:SucursalTipo', 'b', 'WITH', 'b.id = a.sucursalTipo')
                ->innerJoin('SieAppWebBundle:Institucioneducativa', 'c', 'WITH', 'c.id = a.institucioneducativa')
//                ->innerJoin('SieAppWebBundle:SuperiorInstitucioneducativaAcreditacion', 'z', 'WITH', 'a.id = z.institucioneducativaSucursal')
                ->innerJoin('SieAppWebBundle:GestionTipo', 'd', 'WITH', 'd.id = a.gestionTipo') 
                ->leftJoin('SieAppWebBundle:InstitucioneducativaSucursalTramite', 'g', 'WITH', 'g.institucioneducativaSucursal = a.id')
                ->leftJoin('SieAppWebBundle:TramiteEstado', 'h', 'WITH', 'h.id = g.tramiteEstado') 
                ->where('c.id = '.$ie_id)
                ->andWhere('a.periodoTipoId = 2 or a.periodoTipoId = 3')
                ->groupBy('d.id, b.id, a.id, a.periodoTipoId, h.id')
                ->orderBy('d.id, b.id, a.id, a.periodoTipoId')
                ;
        
        return $qb->getQuery()->getResult();
    }
    public function getAllSucursalTipoPer($ie_id) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('d.id as gestionTipo, b.id as SucursalIE, a.id as IEsucursalId, a.periodoTipoId, h.id as teid, h.tramiteEstado as te, h.obs as observacion')
            ->from('SieAppWebBundle:InstitucioneducativaSucursal', 'a')
            ->innerJoin('SieAppWebBundle:SucursalTipo', 'b', 'WITH', 'b.id = a.sucursalTipo')
            ->innerJoin('SieAppWebBundle:Institucioneducativa', 'c', 'WITH', 'c.id = a.institucioneducativa')
//                ->innerJoin('SieAppWebBundle:SuperiorInstitucioneducativaAcreditacion', 'z', 'WITH', 'a.id = z.institucioneducativaSucursal')
            ->innerJoin('SieAppWebBundle:GestionTipo', 'd', 'WITH', 'd.id = a.gestionTipo')
            ->leftJoin('SieAppWebBundle:InstitucioneducativaSucursalTramite', 'g', 'WITH', 'g.institucioneducativaSucursal = a.id')
            ->leftJoin('SieAppWebBundle:TramiteEstado', 'h', 'WITH', 'h.id = g.tramiteEstado')
            ->where('c.id = '.$ie_id)
            ->andWhere('a.periodoTipoId = 1')
            ->groupBy('d.id, b.id, a.id, a.periodoTipoId, h.id')
            ->orderBy('d.id, b.id, a.id, a.periodoTipoId')
        ;

        return $qb->getQuery()->getResult();
    }




}
