<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InstitucioneducativaEspecialidadTecnicoHumanisticoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitucioneducativaEspecialidadTecnicoHumanisticoRepository extends EntityRepository {
/*
select ieeth.id as ieethId,  etht.id as ethtId, etht.especialidad
from institucioneducativa_especialidad_tecnico_humanistico ieeth
left join especialidad_tecnico_humanistico_tipo etht on (ieeth.especialidad_tecnico_humanistico_tipo_id = etht.id)
where institucioneducativa_id = 80980064
order by etht.especialidad
*/
  public function getSpecialityByUnidadEducativa($sie, $gestion) {
      $qb = $this->getEntityManager()->createQueryBuilder();
      $qb
              //->select('e.id as idStudent, e.paterno, e.materno, e.nombre, e.fechaNacimiento, nt.nivel, gt.grado, pt.paralelo,tt.turno, IDENTITY(ei.estadomatriculaTipo), emt.estadomatricula, get.genero')
              ->select('ieeth.id as ieethId,  etht.id as ethtId, etht.especialidad')
              ->from('SieAppWebBundle:InstitucioneducativaEspecialidadTecnicoHumanistico', 'ieeth')
              ->leftJoin('SieAppWebBundle:EspecialidadTecnicoHumanisticoTipo', 'etht', 'WITH', 'ieeth.especialidadTecnicoHumanisticoTipo = etht.id')
              ->where('ieeth.institucioneducativa = :sie')
              ->andwhere('ieeth.gestionTipo = :gestion')
              ->setParameter('sie', $sie)
              ->setParameter('gestion', $gestion)
              ->orderBy('etht.especialidad')
              ;
      return $qb->getQuery()->getResult();
  }

  public function getSpecialityPerStudent($eInsId) {
      $qb = $this->getEntityManager()->createQueryBuilder();
      $qb
              //->select('e.id as idStudent, e.paterno, e.materno, e.nombre, e.fechaNacimiento, nt.nivel, gt.grado, pt.paralelo,tt.turno, IDENTITY(ei.estadomatriculaTipo), emt.estadomatricula, get.genero')
              ->select(' eiht.horas as horas, etht.especialidad as especialidad ')
              ->from('SieAppWebBundle:EstudianteInscripcionHumnisticoTecnico', 'eiht')
              ->leftJoin('SieAppWebBundle:EspecialidadTecnicoHumanisticoTipo', 'etht', 'WITH', 'eiht.especialidadTecnicoHumanisticoTipo = etht.id')
              ->where('eiht.estudianteInscripcion = :eInsId')
              ->setParameter('eInsId', $eInsId)
              ;
      return $qb->getQuery()->getResult();
  }

  /*
  select ieeth.id, ieeth.institucioneducativa_id, etht.id, etht.especialidad
  from institucioneducativa_especialidad_tecnico_humanistico ieeth
  left join especialidad_tecnico_humanistico_tipo etht on (ieeth.especialidad_tecnico_humanistico_tipo_id = etht.id)
  where ieeth.institucioneducativa_id = 80930002 and ieeth.gestion_tipo_id = 2016
  */
  public function getSpecialityPerUE($sie, $gestion){
    $qb = $this->getEntityManager()->createQueryBuilder();
    $qb
            //->select('e.id as idStudent, e.paterno, e.materno, e.nombre, e.fechaNacimiento, nt.nivel, gt.grado, pt.paralelo,tt.turno, IDENTITY(ei.estadomatriculaTipo), emt.estadomatricula, get.genero')
            ->select(' ieeth.id as ieethId, IDENTITY(ieeth.institucioneducativa) as sie, IDENTITY(ieeth.gestionTipo) as gestion,  etht.id as specialidadId, etht.especialidad as especialidad ')
            ->from('SieAppWebBundle:InstitucioneducativaEspecialidadTecnicoHumanistico', 'ieeth')
            ->leftJoin('SieAppWebBundle:EspecialidadTecnicoHumanisticoTipo', 'etht', 'WITH', 'ieeth.especialidadTecnicoHumanisticoTipo = etht.id')
            ->where('ieeth.institucioneducativa = :sie')
            ->andwhere('ieeth.gestionTipo = :gestion')
            ->setParameter('sie',$sie)
            ->setParameter('gestion', $gestion)
            ;
    return $qb->getQuery()->getResult();
  }
}
