<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\Types\Type;
Type::overrideType('datetime', 'Doctrine\DBAL\Types\VarDateTimeType');

/**
 * InstitucioneducativaHumanisticoTecnicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitucioneducativaHumanisticoTecnicoRepository extends EntityRepository {

    public function getSelectAll() {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
                ->select('i')
                ->from('SieAppWebBundle:InstitucioneducativaHumanisticoTecnico', 'i')
                ->orderby('i.institucioneducativa');
        return $qb->getQuery()->getResult();
    }
    public function getTypeOfUE($data) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
                ->select('ieht')
                ->from('SieAppWebBundle:InstitucioneducativaHumanisticoTecnico', 'ieht')
                ->where('ieht.institucioneducativaId = :sie')
                ->andwhere('ieht.gestionTipoId = :gestion')
                ->setParameter('sie', $data['sie'])
                ->setParameter('gestion', $data['gestion'])
                // ->orderby('ieht.institucioneducativa')
                ;

        return $qb->getQuery()->getResult();
    }

}
