<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InstitucioneducativaCursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitucioneducativaCursoRepository extends EntityRepository
{
    public function getAlterCursosBySieGestSubPer($ie_id, $ie_gestion, $ie_subcea, $per_id_cod) {
        $qb = $this->getEntityMAnager()->createQueryBuilder();
        $qb
                ->select('h.id as iecId, a.codigo as nivelId, a.facultadArea as nivel, b.codigo as cicloId, b.especialidad as ciclo,
                 d.codigo as gradoId, d.acreditacion as grado, q.id as turnoId, q.turno, p.id as paraleloId, p.paralelo,
                 b.codigo as setCodigo, d.codigo as satCodigo
                 ')
                ->from('SieAppWebBundle:SuperiorFacultadAreaTipo', 'a')
                ->innerJoin('SieAppWebBundle:SuperiorEspecialidadTipo', 'b', 'WITH', 'a.id = b.superiorFacultadAreaTipo')
                ->innerJoin('SieAppWebBundle:SuperiorAcreditacionEspecialidad', 'c', 'WITH', 'b.id = c.superiorEspecialidadTipo')
                ->innerJoin('SieAppWebBundle:SuperiorAcreditacionTipo', 'd', 'WITH', 'c.superiorAcreditacionTipo = d.id')
                ->innerJoin('SieAppWebBundle:SuperiorInstitucioneducativaAcreditacion', 'e', 'WITH', 'e.acreditacionEspecialidad = c.id')
                ->innerJoin('SieAppWebBundle:InstitucioneducativaSucursal', 'f', 'WITH', 'e.institucioneducativaSucursal = f.id')
                ->innerJoin('SieAppWebBundle:SuperiorInstitucioneducativaPeriodo', 'g', 'WITH', 'g.superiorInstitucioneducativaAcreditacion = e.id')
                ->innerJoin('SieAppWebBundle:InstitucioneducativaCurso', 'h', 'WITH', 'h.superiorInstitucioneducativaPeriodo = g.id')
                ->innerJoin('SieAppWebBundle:ParaleloTipo', 'p', 'WITH', 'h.paraleloTipo = p.id')
                ->innerJoin('SieAppWebBundle:TurnoTipo', 'q', 'WITH', 'h.turnoTipo  = q.id')
                ->where('h.institucioneducativa = :sie')
                ->andwhere('h.gestionTipo = :gestion')
                ->andwhere('f.sucursalTipo = :sucursal')
                ->andwhere('f.periodoTipoId = :periodo')
                ->groupBy('h.id, a.codigo, a.facultadArea, b.codigo, b.especialidad, d.codigo, d.acreditacion, q.id, p.id')
                ->orderBy('a.codigo, b.codigo, d.codigo, p.id')
                ->setParameter('sie', $ie_id)
                ->setParameter('gestion', $ie_gestion)
                ->setParameter('sucursal', $ie_subcea)
                ->setParameter('periodo', $per_id_cod)
        ;
        return $qb->getQuery()->getResult();
    }

    public function getListStudentPerCourseAlter($ie_curso_id) {
        $qb = $this->getEntityMAnager()->createQueryBuilder();
        $qb

                ->select('emt.estadomatricula, emt.id as estadomatriculaId, j.id, j.carnetIdentidad, j.codigoRude, j.paterno, j.materno, j.nombre, j.fechaNacimiento, i.id as eInsId, a.codigo as nivelId, b.codigo as cicloId, d.codigo as gradoId')
                ->from('SieAppWebBundle:SuperiorFacultadAreaTipo', 'a')
                ->innerJoin('SieAppWebBundle:SuperiorEspecialidadTipo', 'b', 'WITH', 'a.id = b.superiorFacultadAreaTipo')
                ->innerJoin('SieAppWebBundle:SuperiorAcreditacionEspecialidad', 'c', 'WITH', 'b.id = c.superiorEspecialidadTipo')
                ->innerJoin('SieAppWebBundle:SuperiorAcreditacionTipo', 'd', 'WITH', 'c.superiorAcreditacionTipo=d.id')
                ->innerJoin('SieAppWebBundle:SuperiorInstitucioneducativaAcreditacion', 'e', 'WITH', 'e.acreditacionEspecialidad=c.id')
                ->innerJoin('SieAppWebBundle:SuperiorInstitucioneducativaPeriodo', 'g', 'WITH', 'g.superiorInstitucioneducativaAcreditacion=e.id')
                ->innerJoin('SieAppWebBundle:InstitucioneducativaCurso', 'h', 'WITH', 'h.superiorInstitucioneducativaPeriodo=g.id')
                ->innerJoin('SieAppWebBundle:EstudianteInscripcion', 'i', 'WITH', 'h.id=i.institucioneducativaCurso')
                ->innerJoin('SieAppWebBundle:Estudiante', 'j', 'WITH', 'i.estudiante=j.id')
                ->innerJoin('SieAppWebBundle:EstadomatriculaTipo', 'emt', 'WITH', 'i.estadomatriculaTipo = emt.id')
                ->where('h.id = :ie_curso_id')
                ->orderBy('j.paterno, j.materno, j.nombre')
                ->setParameter('ie_curso_id', $ie_curso_id)
        ;
        return $qb->getQuery()->getResult();
    }

    public function getListStudentPerCourseTodoInscriptionAlter($ie_id, $ie_gestion, $ie_subcea, $per_id_cod, $realLevel, $setCodigo, $satCodigo, $paralelo, $turno) {
        $qb = $this->getEntityMAnager()->createQueryBuilder();//echo "$ie_id, $ie_gestion, $ie_subcea, $per_id_cod, $realLevel";
        $qb

                ->select('emt.estadomatricula, emt.id as estadomatriculaId, j.id, j.carnetIdentidad, j.codigoRude, j.paterno, j.materno, j.nombre, j.fechaNacimiento, i.id as eInsId, a.codigo as nivelId, b.codigo as cicloId, d.codigo as gradoId')
                ->from('SieAppWebBundle:SuperiorFacultadAreaTipo', 'a')
                ->innerJoin('SieAppWebBundle:SuperiorEspecialidadTipo', 'b', 'WITH', 'a.id = b.superiorFacultadAreaTipo')
                ->innerJoin('SieAppWebBundle:SuperiorAcreditacionEspecialidad', 'c', 'WITH', 'b.id = c.superiorEspecialidadTipo')
                ->innerJoin('SieAppWebBundle:SuperiorAcreditacionTipo', 'd', 'WITH', 'c.superiorAcreditacionTipo=d.id')
                ->innerJoin('SieAppWebBundle:SuperiorInstitucioneducativaAcreditacion', 'e', 'WITH', 'e.acreditacionEspecialidad=c.id')
                ->innerJoin('SieAppWebBundle:InstitucioneducativaSucursal', 'f', 'WITH', 'e.institucioneducativaSucursal = f.id')
                ->innerJoin('SieAppWebBundle:SuperiorInstitucioneducativaPeriodo', 'g', 'WITH', 'g.superiorInstitucioneducativaAcreditacion=e.id')
                ->innerJoin('SieAppWebBundle:InstitucioneducativaCurso', 'h', 'WITH', 'h.superiorInstitucioneducativaPeriodo=g.id')
                ->innerJoin('SieAppWebBundle:EstudianteInscripcion', 'i', 'WITH', 'h.id=i.institucioneducativaCurso')
                ->innerJoin('SieAppWebBundle:Estudiante', 'j', 'WITH', 'i.estudiante=j.id')
                ->innerJoin('SieAppWebBundle:EstadomatriculaTipo', 'emt', 'WITH', 'i.estadomatriculaTipo = emt.id')

                ->where('h.institucioneducativa = :sie')
                ->andwhere('h.gestionTipo = :gestion')
                ->andwhere('f.sucursalTipo = :sucursal')
                ->andwhere('f.periodoTipoId = :periodo')
                ->andwhere('a.codigo = :realLevel')
                ->andwhere('b.codigo = :setCodigo')
                ->andwhere('d.codigo = :satCodigo')
                ->andwhere('h.paraleloTipo = :paralelo')
                ->andwhere('h.turnoTipo = :turno')

                ->setParameter('sie', $ie_id)
                ->setParameter('gestion', $ie_gestion)
                ->setParameter('sucursal', $ie_subcea)
                ->setParameter('periodo', $per_id_cod)
                ->setParameter('realLevel', $realLevel)
                ->setParameter('setCodigo', $setCodigo)
                ->setParameter('satCodigo', $satCodigo)
                ->setParameter('paralelo', $paralelo)
                ->setParameter('turno', $turno)

                ->orderBy('j.paterno, j.materno, j.nombre')
        ;//dump($qb->getQuery()->getSQL());die;
        return $qb->getQuery()->getResult();
    }

    public function getStudentsTodoInscription($ie_id, $ie_gestion, $ie_subcea, $per_id_cod, $realLevel) {
        $qb = $this->getEntityMAnager()->createQueryBuilder();
        $qb
                ->select('h.id as iecId, a.codigo as nivelId, a.facultadArea as nivel, b.codigo as cicloId, b.especialidad as ciclo,
                 d.codigo as gradoId, d.acreditacion as grado, q.id as turnoId, q.turno, p.id as paraleloId, p.paralelo, est.codigoRude')
                ->from('SieAppWebBundle:SuperiorFacultadAreaTipo', 'a')
                ->innerJoin('SieAppWebBundle:SuperiorEspecialidadTipo', 'b', 'WITH', 'a.id = b.superiorFacultadAreaTipo')
                ->innerJoin('SieAppWebBundle:SuperiorAcreditacionEspecialidad', 'c', 'WITH', 'b.id = c.superiorEspecialidadTipo')
                ->innerJoin('SieAppWebBundle:SuperiorAcreditacionTipo', 'd', 'WITH', 'c.superiorAcreditacionTipo = d.id')
                ->innerJoin('SieAppWebBundle:SuperiorInstitucioneducativaAcreditacion', 'e', 'WITH', 'e.acreditacionEspecialidad = c.id')
                ->innerJoin('SieAppWebBundle:InstitucioneducativaSucursal', 'f', 'WITH', 'e.institucioneducativaSucursal = f.id')
                ->innerJoin('SieAppWebBundle:SuperiorInstitucioneducativaPeriodo', 'g', 'WITH', 'g.superiorInstitucioneducativaAcreditacion = e.id')
                ->innerJoin('SieAppWebBundle:InstitucioneducativaCurso', 'h', 'WITH', 'h.superiorInstitucioneducativaPeriodo = g.id')

                ->innerJoin('SieAppWebBundle:EstudianteInscripcion', 'ei', 'WITH', 'h.id = ei.institucioneducativaCurso')
                ->innerJoin('SieAppWebBundle:Estudiante', 'est', 'WITH', 'ei.estudiante = est.id')

                ->innerJoin('SieAppWebBundle:ParaleloTipo', 'p', 'WITH', 'h.paraleloTipo = p.id')
                ->innerJoin('SieAppWebBundle:TurnoTipo', 'q', 'WITH', 'h.turnoTipo  = q.id')

                ->where('h.institucioneducativa = :sie')
                ->andwhere('h.gestionTipo = :gestion')
                ->andwhere('f.sucursalTipo = :sucursal')
                ->andwhere('f.periodoTipoId = :periodo')
                ->andwhere('a.codigo = :realLevel')

                ->setParameter('sie', $ie_id)
                ->setParameter('gestion', $ie_gestion)
                ->setParameter('sucursal', $ie_subcea)
                ->setParameter('periodo', $per_id_cod - 1)
                ->setParameter('realLevel', $realLevel)

                ->orderBy('a.codigo, b.codigo, d.codigo, p.id')
        ;
        return $qb->getQuery()->getResult();
    }

    /**
    *method to find the modules per course to the alternativa
    *return array wiht the modules
    **/
    public function findModulesByCourse($data){
      $qb = $this->getEntityMAnager()->createQueryBuilder();
      $qb
              ->select('iec.id as iecId, ieco.id as iecoId, smp.id as smpId, smt.id as smtId, smt.modulo as modulo')
              ->from('SieAppWebBundle:InstitucioneducativaCurso', 'iec')
              ->innerJoin('SieAppWebBundle:InstitucioneducativaCursoOferta', 'ieco', 'WITH', 'iec.id = ieco.insitucioneducativaCurso')
              ->innerJoin('SieAppWebBundle:SuperiorModuloPeriodo', 'smp', 'WITH', 'ieco.superiorModuloPeriodo = smp.id')
              ->leftjoin('SieAppWebBundle:SuperiorModuloTipo', 'smt', 'WITH', 'smp.superiorModuloTipo = smt.id')
              ->where('iec.id = :ie_curso_id')
              ->setParameter('ie_curso_id', $data['ueducativaInfoId']['iecId'])
      ;
      return $qb->getQuery()->getResult();
    }



}
