<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InstitucioneducativanoacreditadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitucioneducativanoacreditadoRepository extends EntityRepository {

    /**
     * get number of students per ue unacredit
     * @param type $id
     * @return type
     */
    public function getNumberStudents($id) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
                ->select('ena.nivelId, ena.gradoId, count(ena.institucioneducativanoacreditada) as amount')
                ->from('SieAppWebBundle:Institucioneducativanoacreditado', 'iena')
                ->leftjoin('SieAppWebBundle:Estudiantenoacredidato', 'ena', 'WITH', 'iena.id = ena.institucioneducativanoacreditada')
                ->where('iena.id = :id')
                ->setParameter('id', $id)
                ->groupBy('ena.nivelId, ena.gradoId')
                ->orderBy('ena.nivelId, ena.gradoId');
        return $qb->getQuery()->getResult();
    }

    /*
      select *
      from institucioneducativanoacreditado  iena
      left join estudiantenoacredidato ena on (iena.id = ena.institucioneducativanoacreditada_id)
      where iena.id ='136' and ena.nivel_id = 12 and ena.grado_id=1
     *  */

    public function getStudentsByNivelGrado($sie, $nivel, $grado) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
                ->select('ena.carnetIdentidad,ena.paterno, ena.materno,ena.nombre,  ena.generoTipoId, ena.fechaNacimiento, ena.paralelo, ena.turnoId')
                ->from('SieAppWebBundle:Institucioneducativanoacreditado', 'iena')
                ->leftjoin('SieAppWebBundle:Estudiantenoacredidato', 'ena', 'WITH', 'iena.id = ena.institucioneducativanoacreditada')
                ->where('iena.id = :sie')
                ->andwhere('ena.nivelId = :nivel')
                ->andwhere('ena.gradoId = :grado')
                ->setParameter('sie', $sie)
                ->setParameter('nivel', $nivel)
                ->setParameter('grado', $grado)
                ->orderBy('ena.paterno, ena.materno');
        return $qb->getQuery()->getResult();
    }

}
