<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InstitucioneducativaNivelAutorizadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitucioneducativaNivelAutorizadoRepository extends EntityRepository
{
    public function getInfoAutorizadaUe($sie, $gestion) {
       $qb = $this->getEntityManager()->createQueryBuilder();
       $qb
               ->select('iena.id, IDENTITY(iena.institucioneducativa) as institucioneducativaId , nt.nivel')
               ->from('SieAppWebBundle:InstitucioneducativaNivelAutorizado', 'iena')
               ->leftjoin('SieAppWebBundle:NivelTipo', 'nt', 'WITH', 'iena.nivelTipo = nt.id')
               ->where('iena.institucioneducativaId = :sie')
               ->andwhere('iena.gestionTipoId = :gestion')
               ->setParameter('sie', $sie)
               ->setParameter('gestion', $gestion)
       ;
       return $qb->getQuery()->getResult();
   }
}
