<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JdpPruebaParticipacionTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JdpPruebaParticipacionTipoRepository extends EntityRepository
{
}
