<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LugarTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LugarTipoRepository extends EntityRepository
{
	/* ///////////////////////////////
	 *	DATOS CENSO 2012
	 */////////////////////////////////
	// Provincias 2012
	public function provincias2012($departamento) {
		$qb = $this->getEntityManager()->createQueryBuilder();
		$prov =	$qb->select('lt.id, lt.lugar')
                ->from('SieAppWebBundle:LugarTipo','lt')
                ->where('lt.lugarNivel = 9')
                ->andWhere('lt.lugarTipo = :dep')
                ->setParameter('dep',$departamento)
                ->getQuery()
                ->getResult();

        $provincia = array();
        foreach ($prov as $p) {
            $provincia[$p['id']] = $p['lugar'];
        }
        return $provincia;
    }

    // Municipios 2012
	public function municipios2012($provincia) {
		$qb = $this->getEntityManager()->createQueryBuilder();
		$muni =	$qb->select('lt.id, lt.lugar')
                ->from('SieAppWebBundle:LugarTipo','lt')
                ->where('lt.lugarNivel = 10')
                ->andWhere('lt.lugarTipo = :prov')
                ->setParameter('prov',$provincia)
                ->getQuery()
                ->getResult();

        $municipio = array();
        foreach ($muni as $m) {
            $municipio[$m['id']] = $m['lugar'];
        }
        return $municipio;
    }

    // Comunidades 2012
	public function comunidades2012($municipio) {
		$qb = $this->getEntityManager()->createQueryBuilder();
		$comu =	$qb->select('lt.id, lt.lugar')
                ->from('SieAppWebBundle:LugarTipo','lt')
                ->where('lt.lugarNivel = 11')
                ->andWhere('lt.lugarTipo = :mun')
                ->setParameter('mun',$municipio)
                ->getQuery()
                ->getResult();

        $comunidad = array();
        foreach ($comu as $c) {
            $comunidad[$c['id']] = $c['lugar'];
        }
        return $comunidad;
    }

    // Provincias 2012
	public function localidades2012($comunidad) {
		$qb = $this->getEntityManager()->createQueryBuilder();
		$local =	$qb->select('lt.id, lt.lugar')
                ->from('SieAppWebBundle:LugarTipo','lt')
                ->where('lt.lugarNivel = 12')
                ->andWhere('lt.lugarTipo = :comu')
                ->setParameter('comu',$comunidad)
                ->getQuery()
                ->getResult();
        //$prov = $em->getRepository('SieAppWebBundle:LugarTipo')->findBy(array('lugarNivel' => 9, 'lugarTipo' => $departamento));
        $localidad = array();
        foreach ($local as $l) {
            $localidad[$l['id']] = $l['lugar'];
        }
        return $localidad;
    }
}
