<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegistroConsolidacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroConsolidacionRepository extends EntityRepository {

    public function getGestionBySie($sie) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
                ->select('rc')
                ->from('SieAppWebBundle:RegistroConsolidacion', 'rc')
                ->leftJoin('SieAppWebBundle:Institucioneducativa', 'ie', 'WITH', 'rc.unidadEducativa = ie.id')
                ->where('rc.unidadEducativa = :sie')
                //->andwhere('rc.gestion > :gestion')
                ->setParameter('sie', $sie)
                //->setParameter('gestion', '2014')
                ->orderBy('rc.gestion', 'ASC')
        ;
        return $qb->getQuery()->getResult();
    }

    public function getBimestreBySieAndGestion($sie, $gestion) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
                ->select('rc')
                ->from('SieAppWebBundle:RegistroConsolidacion', 'rc')
                ->leftJoin('SieAppWebBundle:Institucioneducativa', 'ie', 'WITH', 'rc.unidadEducativa = ie.id')
                ->where('rc.unidadEducativa = :sie')
                ->andwhere('rc.gestion = :gestion')
                ->setParameter('sie', $sie)
                ->setParameter('gestion', $gestion)
                ->orderBy('rc.gestion')
        ;
        return $qb->getQuery()->getResult();
    }

}
