<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RolRolesAsignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolRolesAsignacionRepository extends EntityRepository
{
    public function getFindRolesByUsername($roluser, $arrayroles) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        if ($arrayroles == ''){
            $qb
                ->select('b.id')
                ->from('SieAppWebBundle:RolRolesAsignacion', 'a')
                ->innerJoin('SieAppWebBundle:RolTipo', 'b', 'WITH', 'b.id = a.roles')
                ->where("a.rol = '".$roluser."'")
                ->orderBy('a.roles');
        }
        else{
            $qb
                ->select('b.id')
                ->from('SieAppWebBundle:RolRolesAsignacion', 'a')
                ->innerJoin('SieAppWebBundle:RolTipo', 'b', 'WITH', 'b.id = a.roles')
                ->where("a.rol = '".$roluser."'")
                ->andwhere("a.roles IN (".$arrayroles.")")
                ->orderBy('a.roles');
        }
        
        
        return $qb->getQuery()->getResult();
    } 
    
    public function getFindByNotUserRolesId($roluser, $userid) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb2 = $this->getEntityManager()->createQueryBuilder();
        $sub = $qb->select('e')            
            ->from('SieAppWebBundle:UsuarioRol', 'd')
            ->innerJoin('SieAppWebBundle:RolTipo', 'e', 'WITH', 'e.id = d.rolTipo')                
            ->where($qb->expr()->eq('d.usuario',$userid))
            ->getQuery()
            ->getResult();
        $ids = '';

        if (count($sub) > 0){
            foreach ($sub as $somevar){
                $ids = $ids.','.$somevar->getId();   
                }
            $ids = substr($ids,1); 
            $rolesuser = $qb2->select('b.id')
                ->from('SieAppWebBundle:RolRolesAsignacion', 'a')
                ->innerJoin('SieAppWebBundle:RolTipo', 'b', 'WITH', 'b.id = a.roles')
                ->where("a.rol = '".$roluser."'")
                ->andwhere($qb->expr()->notIn('b.id', $ids))
                ->orderBy('a.roles')
                ->getQuery()
                ->getResult();
        }    
        else{
            $rolesuser = $qb2->select('b.id')
                ->from('SieAppWebBundle:RolRolesAsignacion', 'a')
                ->innerJoin('SieAppWebBundle:RolTipo', 'b', 'WITH', 'b.id = a.roles')
                ->where("a.rol = '".$roluser."'")                
                ->orderBy('a.roles')
                ->getQuery()
                ->getResult();
        }         
        return $rolesuser;     
    }
}
