<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RudeAtencionIndirectaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below. RUDE 2024
 */
class RudeAtencionIndirectaRepository extends EntityRepository
{
}
