<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TmpInstitucioneducativaApertura2021Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TmpInstitucioneducativaApertura2021Repository extends EntityRepository
{
}
