<?php

namespace Sie\AppWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ValidacionProcesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValidacionProcesoRepository extends EntityRepository{
      /**
       * get the validation process info
       * @param type $id
       * @return array with infot about validation process
       */
       /*
        select vp.fecha_proceso, vp.llave, vp.gestion_tipo_id, vp.obs, vret.entidad, vp.es_activo
        from validacion_proceso vp
        left join validacion_regla_tipo vrt on (vp.validacion_regla_tipo_id=vrt.id)
        left join validacion_regla_entidad_tipo vret on (vrt.validacion_regla_entidad_tipo_id = vret.id)
        where vp.llave = '82200063' and vp.gestion_tipo_id='2016' and vp.es_activo='t'
       */
      public function getValidationProcessInfo($data) {
          $qb = $this->getEntityManager()->createQueryBuilder();
          $qb
                  ->select(' vp.fechaProceso, vp.llave, IDENTITY(vp.gestionTipo) as gestionTipo, vp.obs, vret.entidad, vp.esActivo')
                  ->from('SieAppWebBundle:ValidacionProceso', 'vp')
                  ->leftjoin('SieAppWebBundle:ValidacionReglaTipo', 'vrt', 'WITH', 'vp.validacionReglaTipo=vrt.id')
                  ->leftjoin('SieAppWebBundle:validacionReglaEntidadTipo', 'vret', 'WITH', 'vrt.validacionReglaEntidadTipo = vret.id')
                  ->where('vp.llave = :sie')
                  ->andwhere('vp.gestionTipo = :gestion')
                  ->andwhere('vp.esActivo = :activo')
                  ->setParameter('sie', $data['sie'])
                  ->setParameter('gestion', $data['gestion'])
                  ->setParameter('activo', 't');
                  //->setParameter('')
          return $qb->getQuery()->getResult();
      }
      public function getNacFechaAndGeneroInfo($rude, $yearQA){
        // dump($rude);die;
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
                ->select('vp')
                ->from('SieAppWebBundle:ValidacionProceso', 'vp')
                ->where('vp.llave = :rude')
                ->andwhere('vp.validacionReglaTipo IN (:vregla)')
                ->andwhere('vp.esActivo = :activo')
                ->andwhere('vp.gestionTipo = :gestion')
                ->setParameter('rude', $rude)
                ->setParameter('vregla', array(2,3))
                ->setParameter('activo', 'f')
                ->setParameter('gestion', $yearQA);

        return $qb->getQuery()->getResult();
      }

      public function getObservationPerSie($data) {
        // dump($data);
          $qb = $this->getEntityManager()->createQueryBuilder();
          $qb
                  ->select(' vp.fechaProceso, vp.llave, IDENTITY(vp.gestionTipo) as gestionTipo, vp.obs, vret.entidad, vp.esActivo')
                  ->from('SieAppWebBundle:ValidacionProceso', 'vp')
                  ->leftjoin('SieAppWebBundle:ValidacionReglaTipo', 'vrt', 'WITH', 'vp.validacionReglaTipo=vrt.id')
                  ->leftjoin('SieAppWebBundle:validacionReglaEntidadTipo', 'vret', 'WITH', 'vrt.validacionReglaEntidadTipo = vret.id')
                  ->where('vp.institucionEducativaId = :sie')
                  ->andwhere('vp.gestionTipo = :gestion')
                  ->andwhere('vp.esActivo = :activo')
                  ->setParameter('sie', $data['sie'])
                  ->setParameter('gestion', $data['gestion'])
                  ->setParameter('activo', 'f')
                  ;
                  //->setParameter('')
                  // dump($qb->getQuery()->getSQL());die;
          return $qb->getQuery()->getResult();
      }
}
